on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        name: Version evaluation
      - name: Zip and push
        # if: ${{ steps.release.outputs.release_created }}
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          echo "release_created?"
          echo ${{ steps.release.outputs.release_created }} ? 'true' : 'false'
          echo "paths_released: ${{ steps.release.outputs.paths_released }}"
          echo "prs_created?"
          echo ${{ steps.release.outputs.prs_created }} ? 'true' : 'false'
          echo "pr: ${{ steps.release.outputs.pr }}"
          echo "prs: ${{ steps.release.outputs.prs }}"
